#!/usr/bin/env bash

script_name="${0##*/}"

echo "${script_name}: '$(pwd)'"

progs="autoconf automake autopoint gettext libtoolize make pkg-config"
for p in ${progs}; do
	if ! test -x "$(command -v ${p})"; then
		echo "${script_name}: ERROR: Please install '${p}'." >&2
		result=1
	fi
done

if [[ ! -e '/usr/include/murmurhash.h' ]]; then
	echo "${script_name}: INFO: Consider installing libmurmurhash-dev." >&2
fi

if [[ ${result} ]]; then
	exit 1
fi

mkdir -p m4
exec autoreconf --force --install ${@}
